sonar.exclusions=src/mocks/**,e2e/**,**/*.test.ts,**/*.test.tsx,**/*.styles.test.tsx
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.organization=alexandre-s-goncalves
sonar.projectKey=northern-route-web
sonar.projectName=NorthernRoute Web
sonar.projectVersion=1.0.0
sonar.sources=src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx
sonar.tests=src
